### ISSUE TITLE
Create a result view if the user finished the level

### ISSUE THREAD

**Issue by Portals** [cthit/CodeIT#24]
* Show text, e.g. "You have won!"
* If the level had a score (e.g. the amount of coins), show the score. 
* If the level has a time limit, show the finish time.
* Have a button to the main menu (which has all the available levels).
* Have a button to the next level

**Comment by ViddeM** [comment]
All of the points above a part from the time left was is done.

**Comment by Portals** [comment]
Can it be done before CodeIT? @viddeM
