### ISSUE TITLE
Support png, jpg and gif everywhere

### ISSUE THREAD

**Issue by Portals** [cthit/CodeIT#30]
Entities, backgrounds etc. If pygame natively supports it.

**Comment by NeonSky** [comment]
@Portals ?

**Comment by Portals** [comment]
I talked to Iller, and CodeIT aöready tries to load whatever the type may be.

**Comment by NeonSky** [comment]
What about these?
Tile.py:24
GuiElement.py:19

**Comment by elias-sundqvist** [comment]
Yes, those still need to be fixed. Entities and backgrounds load as expected regardless of file extension though.
